apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: corporate-catering-default-deny
  labels:
    app.kubernetes.io/name: corporate-catering-default-deny
    app.kubernetes.io/part-of: corporate-catering-system
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
