apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: corporate-catering-postgres
  labels:
    app.kubernetes.io/name: corporate-catering-postgres
    app.kubernetes.io/part-of: corporate-catering-system
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 100Gi
  walStorage:
    size: 20Gi
  certificates:
    serverTLSSecret: corporate-catering-postgres-server-tls
    serverCASecret: corporate-catering-postgres-ca
    clientCASecret: corporate-catering-postgres-client-ca
  bootstrap:
    initdb:
      database: corporate_catering
      owner: corporate_catering
      secret:
        name: corporate-catering-postgres-app-user
  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: corporate-catering-postgres-rw
              labels:
                app.kubernetes.io/name: corporate-catering-postgres-rw
                app.kubernetes.io/part-of: corporate-catering-system
            spec:
              type: ClusterIP
              ports:
                - name: postgres
                  port: 5432
                  targetPort: 5432
        - selectorType: ro
          serviceTemplate:
            metadata:
              name: corporate-catering-postgres-ro
              labels:
                app.kubernetes.io/name: corporate-catering-postgres-ro
                app.kubernetes.io/part-of: corporate-catering-system
            spec:
              type: ClusterIP
              ports:
                - name: postgres
                  port: 5432
                  targetPort: 5432
  monitoring:
    enablePodMonitor: true
