apiVersion: v1
kind: Service
metadata:
  name: web-merchant
  namespace: tbite
  labels:
    app.kubernetes.io/name: web-merchant
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: tbite
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: web-merchant
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
