apiVersion: v1
kind: ServiceAccount
metadata:
  name: tbite-api
  namespace: tbite
  labels:
    app.kubernetes.io/part-of: tbite
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: false
