apiVersion: v1
kind: Service
metadata:
  name: corporate-catering-api
  labels:
    app.kubernetes.io/name: corporate-catering-api
    app.kubernetes.io/part-of: corporate-catering-system
spec:
  selector:
    app.kubernetes.io/name: corporate-catering-api
  ports:
    - name: http
      port: 80
      targetPort: http
