{{- $cfg := .Values.workers.payrollSettler -}}
{{- if $cfg.enabled }}
{{- $role := "worker-payroll-settler" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tbite.roleFullname" (dict "ctx" . "role" $role) }}
  namespace: {{ include "tbite.namespace" . }}
  labels:
    {{- include "tbite.roleLabels" (dict "ctx" . "role" $role) | nindent 4 }}
spec:
  {{- if not $cfg.keda.enabled }}
  replicas: {{ $cfg.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      {{- include "tbite.roleSelectorLabels" (dict "ctx" . "role" $role) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tbite.roleSelectorLabels" (dict "ctx" . "role" $role) | nindent 8 }}
        {{- include "tbite.podLabels" . | nindent 8 }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap-app-env.yaml") . | sha256sum }}
        {{- include "tbite.podAnnotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "tbite.roleServiceAccountName" (dict "ctx" . "role" $role) }}
      automountServiceAccountToken: false
      {{- include "tbite.imagePullSecrets" . | nindent 6 }}
      securityContext:
        {{- include "tbite.podSecurityContext" . | nindent 8 }}
      terminationGracePeriodSeconds: 60
      containers:
        - name: worker
          image: {{ include "tbite.platformImage" . | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          args: {{ toYaml $cfg.args | nindent 12 }}
          ports:
            - name: probe
              containerPort: {{ $cfg.probePort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "tbite.fullname" . }}-app-env
          env:
            {{- include "tbite.appSecretEnv" . | nindent 12 }}
            - name: TBITE_ROLE
              value: payroll-settler
            - name: PROBE_ADDR
              value: {{ printf ":%v" $cfg.probePort | quote }}
            - name: TBITE_NATS_STREAM
              value: {{ $cfg.keda.stream | quote }}
            - name: TBITE_NATS_CONSUMER
              value: {{ $cfg.keda.consumer | quote }}
            {{- include "tbite.dbEnv" . | nindent 12 }}
            {{- include "tbite.otelEnv" . | nindent 12 }}
          readinessProbe:
            {{- include "tbite.tcpProbe" (dict "port" "probe") | nindent 12 }}
          livenessProbe:
            {{- include "tbite.tcpProbe" (dict "port" "probe") | nindent 12 }}
          resources:
            {{- toYaml $cfg.resources | nindent 12 }}
          securityContext:
            {{- include "tbite.containerSecurityContext" . | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- include "tbite.podScheduling" . | nindent 6 }}
{{- end }}
