{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tbite.fullname" . }}-allow-gateway-ingress
  namespace: {{ include "tbite.namespace" . }}
  labels:
    {{- include "tbite.labels" . | nindent 4 }}
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values: ["api", "realtime", "web-employee", "web-merchant", "web-admin"]
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: {{ .Values.api.port }}
        - protocol: TCP
          port: {{ .Values.realtime.port }}
        - protocol: TCP
          port: {{ .Values.web.employee.port }}
{{- end }}
