{{- if .Values.web.employee.enabled }}
{{- $role := "web-employee" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tbite.roleFullname" (dict "ctx" . "role" $role) }}
  namespace: {{ include "tbite.namespace" . }}
  labels:
    {{- include "tbite.roleLabels" (dict "ctx" . "role" $role) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "tbite.roleSelectorLabels" (dict "ctx" . "role" $role) | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
{{- end }}
