apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: catering-staging
resources:
  - ../../base
components:
  - ../../components/topology-multi-az
  - ../../components/autoscaling-keda-worker
commonAnnotations:
  runtime.corporate-catering.io/environment: staging
  runtime.corporate-catering.io/scaling-strategy: hpa-plus-keda-worker
  runtime.corporate-catering.io/topology-strategy: multi-az
configMapGenerator:
  - name: corporate-catering-overlay-settings
    literals:
      - secretPathPrefix=staging
generatorOptions:
  disableNameSuffixHash: true
patches:
  - path: patch-runtime-values.yaml
  - path: patch-autoscaling.yaml
  - path: patch-gateway.yaml
  - target:
      version: v1
      kind: Namespace
      name: catering-prod
    patch: |-
      - op: replace
        path: /metadata/name
        value: catering-staging
replacements:
  - source:
      kind: ConfigMap
      name: corporate-catering-overlay-settings
      fieldPath: data.secretPathPrefix
    targets:
      - select:
          kind: ExternalSecret
          name: corporate-catering-runtime-secrets
        fieldPaths:
          - spec.data.*.remoteRef.key
        options:
          delimiter: /
          index: 0
      - select:
          kind: ExternalSecret
          name: corporate-catering-postgres-app-user
        fieldPaths:
          - spec.data.*.remoteRef.key
        options:
          delimiter: /
          index: 0
      - select:
          kind: ExternalSecret
          name: corporate-catering-postgres-superuser
        fieldPaths:
          - spec.data.*.remoteRef.key
        options:
          delimiter: /
          index: 0
