#!/usr/bin/env python3
"""Generate scripts/dev/seed-p2.sql from the T-Bite design-system mock data.

Usage:
    python3 scripts/dev/gen-seed.py

Reads:  scripts/dev/data/tw_food_delivery_mock_data_mvp.json
Writes: scripts/dev/seed-p2.sql  (deterministic, idempotent pure SQL)

The generated SQL is committed to the repo so that `make seed` runs pure SQL
and does NOT depend on Python. Re-run this script only when the source data or
the mapping rules below change, then commit the regenerated seed-p2.sql.

Determinism:
  * vendor UUIDs are fixed: r001 -> a1111111-1111-1111-1111-111111111111,
    r002 -> a2222222-..2222, ... r009 -> a9999999-..9999,
    r010 -> aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa. (r001-r003 preserve the
    UUIDs used by existing e2e/demo fixtures.)
  * menu_category / menu_item UUIDs use uuid5 over a fixed namespace, so the
    same input always yields the same output.
  * cuisine_category uses the original string ids ('cat-taiwanese' ...).
"""

import json
import os
import uuid

HERE = os.path.dirname(os.path.abspath(__file__))
DATA_PATH = os.path.join(HERE, "data", "tw_food_delivery_mock_data_mvp.json")
OUT_PATH = os.path.join(HERE, "seed-p2.sql")

# Fixed namespace for deterministic uuid5 generation. Do not change once
# committed, or all menu_category/menu_item ids would shift.
NS = uuid.uuid5(uuid.NAMESPACE_URL, "https://tbite.test/seed")

# r00N -> fixed vendor UUID. r001-r003 reuse the original e2e/demo UUIDs
# (a1111111.., a2222222.., a3333333..), continuing the same pattern through r009
# (a9999999..). r010 uses the all-'a' UUID. The first group is always
# 'a' + digit*7; r010 is the special all-'a' case.
VENDOR_HEX = {
    f"r0{n:02d}": (
        f"a{str(n) * 7}-{str(n) * 4}-{str(n) * 4}-{str(n) * 4}-{str(n) * 12}"
    )
    for n in range(1, 10)
}
VENDOR_HEX["r010"] = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"

# cuisine_category id -> banner image file under /brand/categories/.
CATEGORY_BANNER = {
    "cat-taiwanese": "/brand/categories/taiwanese.jpg",
    "cat-breakfast": "/brand/categories/breakfast.jpg",
    "cat-drinks-desserts": "/brand/categories/drinks-desserts.jpg",
    "cat-global-western": "/brand/categories/global-western.jpg",
}

# Legal-name suffix per category flavour. Generic 有限公司 is fine for a dev seed.
LEGAL_SUFFIX = "有限公司"


def menu_category_id(restaurant_id: str, section: str) -> uuid.UUID:
    return uuid.uuid5(NS, f"tbite:menu_category:{restaurant_id}:{section}")


def menu_item_id(item_id: str) -> uuid.UUID:
    return uuid.uuid5(NS, f"tbite:item:{item_id}")


def sql_str(s) -> str:
    """Quote a Python value as a SQL string literal (or NULL)."""
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def sql_text_array(values) -> str:
    """Render a Python list as a Postgres TEXT[] literal."""
    if not values:
        return "ARRAY[]::text[]"
    inner = ", ".join(sql_str(v) for v in values)
    return f"ARRAY[{inner}]"


def main() -> None:
    with open(DATA_PATH, encoding="utf-8") as fh:
        data = json.load(fh)

    categories = data["categories"]
    restaurants = data["restaurants"]

    out = []
    w = out.append

    w("-- scripts/dev/seed-p2.sql")
    w("-- GENERATED by scripts/dev/gen-seed.py from")
    w("-- scripts/dev/data/tw_food_delivery_mock_data_mvp.json. DO NOT EDIT BY HAND;")
    w("-- re-run the generator and commit the result instead.")
    w("--")
    w("-- Idempotent dev seed: 4 cuisine categories, 10 vendors (with branding),")
    w("-- per-store menu sections, 150 menu items + images, and 7 days of meal_supply.")
    w("-- Run after migrations. Safe to run multiple times.")
    w("")
    w("BEGIN;")
    w("")

    # Collect the authoritative id sets so the cleanup block below can purge
    # anything that is NOT part of the current design-system catalog.
    vendor_ids = [VENDOR_HEX[r["id"]] for r in restaurants]
    item_ids = [str(menu_item_id(it["id"])) for r in restaurants for it in r["items"]]

    # ---- cleanup (make this seed authoritative) ---------------------------
    # The very first dev seed shipped 3 differently-named vendors (reusing the
    # r001-r003 UUIDs) and 12 menu items (b1000001..b3000004). Those rows are
    # NOT in the current catalog, so leaving them around = stale duplicates.
    # Purge everything that is not part of the sets generated below. Run order
    # respects FKs (order_item.menu_item_id is ON DELETE RESTRICT).
    w("-- ---------------------------------------------------------------------------")
    w("-- Authoritative cleanup: remove rows that are NOT in the current catalog.")
    w("-- Demo orders (recreated by seed-demo.sql against the new ids) are dropped")
    w("-- first so the RESTRICT FK on order_item.menu_item_id does not block the")
    w("-- removal of the old 12 menu items. order_item / order_state_event cascade")
    w("-- via ON DELETE CASCADE on order_id.")
    w("-- ---------------------------------------------------------------------------")
    w("DELETE FROM \"order\" WHERE id IN (")
    w("  'd0000000-0000-0000-0000-000000000001',")
    w("  'd0000000-0000-0000-0000-000000000002',")
    w("  'd0000000-0000-0000-0000-000000000003'")
    w(");")
    w("")
    item_id_list = ",\n  ".join(sql_str(i) for i in item_ids)
    w("-- Drop menu items not in the new 150-item catalog (cascades menu_item_image,")
    w("-- meal_supply, employee_favorite). Safe once the demo orders above are gone.")
    w("DELETE FROM menu_item WHERE id NOT IN (")
    w("  " + item_id_list)
    w(");")
    w("")
    vendor_id_list = ",\n  ".join(sql_str(v) for v in vendor_ids)
    w("-- Drop any vendor not in r001-r010 (cascades its menu_category,")
    w("-- vendor_plant_mapping, vendor_operator_account). None expected today, but")
    w("-- keeps the seed authoritative if future runs change the vendor set.")
    w("DELETE FROM vendor WHERE id NOT IN (")
    w("  " + vendor_id_list)
    w(");")
    w("")
    w("-- Drop plant mappings / operator accounts that no longer match the catalog.")
    w("DELETE FROM vendor_plant_mapping WHERE plant NOT IN ('tn-a', 'tn-b', 'tn-c', 'tn-d');")
    w("")

    # ---- cuisine_category --------------------------------------------------
    w("-- Global cuisine categories (4).")
    w("INSERT INTO cuisine_category (id, name, short_name, description, icon, banner_uri, sort_order)")
    w("VALUES")
    rows = []
    for c in categories:
        banner = CATEGORY_BANNER[c["id"]]
        rows.append(
            "  ({id}, {name}, {short}, {desc}, {icon}, {banner}, {sort})".format(
                id=sql_str(c["id"]),
                name=sql_str(c["name"]),
                short=sql_str(c.get("shortName")),
                desc=sql_str(c.get("description")),
                icon=sql_str(c.get("icon")),
                banner=sql_str(banner),
                sort=c.get("sortOrder", 0),
            )
        )
    w(",\n".join(rows))
    w("ON CONFLICT (id) DO NOTHING;")
    w("")

    # ---- vendor ------------------------------------------------------------
    w("-- Vendors (10). r001-r003 keep the UUIDs used by existing e2e/demo fixtures.")
    w("INSERT INTO vendor (id, display_name, legal_name, contact_email, status, approved_at,")
    w("                    cuisine_category_id, cover_image_uri, logo_uri, rating, rating_count, price_level)")
    w("VALUES")
    rows = []
    for r in restaurants:
        rid = r["id"]
        vid = VENDOR_HEX[rid]
        email = f"{rid}@tbite.test"
        cover = f"/brand/stores/{rid}-cover.jpg"
        logo = f"/brand/logos/{rid}.png"
        rows.append(
            "  ({vid}, {dn}, {ln}, {email}, 'approved', now(), {cat}, {cover}, {logo}, {rating}, {rc}, {price})".format(
                vid=sql_str(vid),
                dn=sql_str(r["name"]),
                ln=sql_str(r["name"] + LEGAL_SUFFIX),
                email=sql_str(email),
                cat=sql_str(r["categoryId"]),
                cover=sql_str(cover),
                logo=sql_str(logo),
                rating=r.get("rating", "NULL"),
                rc=r.get("ratingCount", "NULL"),
                price=sql_str(r.get("priceLevel")),
            )
        )
    w(",\n".join(rows))
    # DO UPDATE (not DO NOTHING): r001-r003 reuse the original seed UUIDs but with
    # new names/branding, so we must overwrite the stale rows rather than skip them.
    w("ON CONFLICT (id) DO UPDATE SET")
    w("  display_name        = EXCLUDED.display_name,")
    w("  legal_name          = EXCLUDED.legal_name,")
    w("  contact_email       = EXCLUDED.contact_email,")
    w("  status              = EXCLUDED.status,")
    w("  approved_at         = EXCLUDED.approved_at,")
    w("  cuisine_category_id = EXCLUDED.cuisine_category_id,")
    w("  cover_image_uri     = EXCLUDED.cover_image_uri,")
    w("  logo_uri            = EXCLUDED.logo_uri,")
    w("  rating              = EXCLUDED.rating,")
    w("  rating_count        = EXCLUDED.rating_count,")
    w("  price_level         = EXCLUDED.price_level,")
    w("  updated_at          = now();")
    w("")

    # ---- vendor_plant_mapping ---------------------------------------------
    # Every vendor maps to all four Tainan plant areas so any employee sees
    # every store (good for demos).
    w("-- Plant mappings: every vendor serves all four plants (tn-a..tn-d).")
    w("INSERT INTO vendor_plant_mapping (vendor_id, plant) VALUES")
    rows = []
    for r in restaurants:
        vid = VENDOR_HEX[r["id"]]
        for plant in ("tn-a", "tn-b", "tn-c", "tn-d"):
            rows.append(f"  ({sql_str(vid)}, {sql_str(plant)})")
    w(",\n".join(rows))
    w("ON CONFLICT (vendor_id, plant) DO NOTHING;")
    w("")

    # ---- menu_category (per-store sections) -------------------------------
    w("-- Per-store menu sections (menu_category).")
    w("INSERT INTO menu_category (id, vendor_id, name, sort_order) VALUES")
    rows = []
    for r in restaurants:
        vid = VENDOR_HEX[r["id"]]
        for idx, section in enumerate(r["menuSections"]):
            cid = menu_category_id(r["id"], section)
            rows.append(f"  ({sql_str(str(cid))}, {sql_str(vid)}, {sql_str(section)}, {idx})")
    w(",\n".join(rows))
    w("ON CONFLICT (id) DO NOTHING;")
    w("")

    # ---- menu_item ---------------------------------------------------------
    w("-- Menu items (150). price_minor stores TWD as integer (matches existing seed).")
    w("INSERT INTO menu_item (id, vendor_id, category_id, name, description, price_minor, tags, badges, status)")
    w("VALUES")
    rows = []
    for r in restaurants:
        vid = VENDOR_HEX[r["id"]]
        for it in r["items"]:
            iid = menu_item_id(it["id"])
            cid = menu_category_id(r["id"], it["section"])
            rows.append(
                "  ({iid}, {vid}, {cid}, {name}, {desc}, {price}, {tags}, ARRAY[]::text[], 'active')".format(
                    iid=sql_str(str(iid)),
                    vid=sql_str(vid),
                    cid=sql_str(str(cid)),
                    name=sql_str(it["name"]),
                    desc=sql_str(it.get("description", "")),
                    price=int(it["priceTwd"]),
                    tags=sql_text_array(it.get("dietaryTags", [])),
                )
            )
    w(",\n".join(rows))
    w("ON CONFLICT (id) DO NOTHING;")
    w("")

    # ---- menu_item_image ---------------------------------------------------
    # Each store shares one representative image (mvpRepresentativeItemImage),
    # mapped to /brand/items/<repr>.jpg. menu_item_image has no unique
    # constraint, so guard with NOT EXISTS for idempotency.
    w("-- Menu item images. Each store shares its representative photo under /brand/items/.")
    w("INSERT INTO menu_item_image (menu_item_id, blob_uri, alt, sort_order)")
    w("SELECT v.menu_item_id, v.blob_uri, v.alt, 0")
    w("FROM (VALUES")
    rows = []
    for r in restaurants:
        repr_id = r["mvpRepresentativeItemId"]
        blob = f"/brand/items/{repr_id}.jpg"
        for it in r["items"]:
            iid = menu_item_id(it["id"])
            rows.append(
                "  ({iid}::uuid, {blob}, {alt})".format(
                    iid=sql_str(str(iid)),
                    blob=sql_str(blob),
                    alt=sql_str(it.get("imageAlt", "")),
                )
            )
    w(",\n".join(rows))
    w(") AS v(menu_item_id, blob_uri, alt)")
    w("WHERE NOT EXISTS (")
    w("  SELECT 1 FROM menu_item_image mii")
    w("  WHERE mii.menu_item_id = v.menu_item_id AND mii.blob_uri = v.blob_uri")
    w(");")
    w("")

    # ---- meal_supply -------------------------------------------------------
    w("-- Meal supply: today + next 6 days for every active item (150 x 7 = 1050 rows).")
    w("INSERT INTO meal_supply (menu_item_id, supply_date, capacity, remain, pickup_window, eta_label, cutoff_at)")
    w("SELECT")
    w("  mi.id,")
    w("  d::date AS supply_date,")
    w("  80 AS capacity,")
    w("  80 AS remain,")
    w("  '11:50-12:10' AS pickup_window,")
    w("  '11:50-12:10' AS eta_label,")
    w("  (d::date + INTERVAL '17 hours')::timestamptz AS cutoff_at")
    w("FROM")
    w("  menu_item mi")
    w("  CROSS JOIN generate_series(CURRENT_DATE, CURRENT_DATE + INTERVAL '6 days', INTERVAL '1 day') AS d")
    w("WHERE mi.status = 'active'")
    w("ON CONFLICT (menu_item_id, supply_date) DO NOTHING;")
    w("")

    # ---- vendor_operator_account ------------------------------------------
    # Mirror the Authentik dev merchant accounts. Authentik stays the source of
    # login claims; this table lets admins see/manage operators from T-Bite.
    w("-- Mirror Authentik dev merchant operator accounts (one per vendor).")
    w("INSERT INTO vendor_operator_account (vendor_id, email, display_name, provider, status, last_synced_at)")
    w("VALUES")
    rows = []
    for r in restaurants:
        rid = r["id"]
        vid = VENDOR_HEX[rid]
        # r001 keeps the canonical e2e-merchant account; others get merchant-r00N.
        if rid == "r001":
            email = "e2e-merchant@tbite.test"
            name = "E2E Merchant"
        else:
            email = f"merchant-{rid}@tbite.test"
            name = r["name"]
        rows.append(
            f"  ({sql_str(vid)}, {sql_str(email)}, {sql_str(name)}, 'authentik', 'active', now())"
        )
    w(",\n".join(rows))
    w("ON CONFLICT (vendor_id, email) DO NOTHING;")
    w("")

    w("COMMIT;")
    w("")

    with open(OUT_PATH, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))

    print(f"wrote {OUT_PATH}")
    print(f"  cuisine_category: {len(categories)}")
    print(f"  vendor:           {len(restaurants)}")
    total_items = sum(len(r['items']) for r in restaurants)
    total_sections = sum(len(r['menuSections']) for r in restaurants)
    print(f"  menu_category:    {total_sections}")
    print(f"  menu_item:        {total_items}")
    print(f"  menu_item_image:  {total_items}")
    print(f"  meal_supply:      {total_items * 7}")


if __name__ == "__main__":
    main()
