-- scripts/dev/seed-demo.sql
-- Demo-friendly seed layered on top of seed-p2.sql.
-- Adds demo employees (one per plant) + a few recent orders so all three web
-- apps look populated. Run after seed-p2.sql. Safe to re-run.
--
-- NOTE: menu_item_image rows for the full 150-item catalog are written by
-- seed-p2.sql now, so this file no longer seeds images. Demo orders reference
-- the deterministic menu_item UUIDs generated by scripts/dev/gen-seed.py for
-- r001-r003 (vendors a1111111.. / a2222222.. / a3333333..).

BEGIN;

-- ---------------------------------------------------------------------------
-- Demo employees
-- e2e-employee@tbite.test is the canonical demo employee (matches Authentik
-- dev blueprint + e2e fixtures). The other four cover plants tn-a..tn-d so the
-- merchant/admin views show a spread of departments. Fixed UUIDs so demo
-- orders can reference them.
-- ---------------------------------------------------------------------------
INSERT INTO "user" (id, primary_email, display_name, role, status, employee_id, plant, department)
VALUES
  ('c0000000-0000-0000-0000-0000000000e1', 'e2e-employee@tbite.test', 'E2E 員工',     'employee', 'active', 'E2E001', 'tn-a', 'IT'),
  ('c0000000-0000-0000-0000-0000000000e2', 'emp-tnb@tbite.test',      '王曉明 (B區)', 'employee', 'active', 'E2E002', 'tn-b', 'Ops'),
  ('c0000000-0000-0000-0000-0000000000e3', 'emp-tnc@tbite.test',      '陳怡君 (C區)', 'employee', 'active', 'E2E003', 'tn-c', 'QA'),
  ('c0000000-0000-0000-0000-0000000000e4', 'emp-tnd@tbite.test',      '林志豪 (D區)', 'employee', 'active', 'E2E004', 'tn-d', 'HR'),
  ('c0000000-0000-0000-0000-0000000000e5', 'emp-tna2@tbite.test',     '張美玲 (A區)', 'employee', 'active', 'E2E005', 'tn-a', 'Finance')
ON CONFLICT (primary_email) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Demo orders
-- Three orders for the demo employee across statuses placed / ready / picked_up
-- so the merchant prep board, pickup view, and employee order history all show
-- data. Fixed order UUIDs make this idempotent. Each order has one order_item.
-- placed_at / ready_at / picked_up_at are set per status to satisfy the
-- lifecycle; totp_secret keeps its column default. Vendors a1111111/a2222222/
-- a3333333 are r001/r002/r003; menu items are their deterministic UUIDs.
-- ---------------------------------------------------------------------------
INSERT INTO "order"
  (id, user_id, vendor_id, plant, supply_date, status, total_price_minor,
   placed_at, cutoff_at, ready_at, picked_up_at)
VALUES
  -- placed today: awaiting cutoff, visible on merchant prep board (r001 炙燒雞腿便當 165)
  ('d0000000-0000-0000-0000-000000000001',
   'c0000000-0000-0000-0000-0000000000e1',
   'a1111111-1111-1111-1111-111111111111',
   'tn-a', CURRENT_DATE, 'placed', 165,
   now() - INTERVAL '2 hours',
   (CURRENT_DATE + INTERVAL '17 hours')::timestamptz,
   NULL, NULL),
  -- ready today: prepared, awaiting pickup (r002 半熟蛋滷肉飯 75)
  ('d0000000-0000-0000-0000-000000000002',
   'c0000000-0000-0000-0000-0000000000e1',
   'a2222222-2222-2222-2222-222222222222',
   'tn-a', CURRENT_DATE, 'ready', 75,
   now() - INTERVAL '3 hours',
   (CURRENT_DATE + INTERVAL '17 hours')::timestamptz,
   now() - INTERVAL '30 minutes', NULL),
  -- picked_up yesterday: completed, shows in order history (r003 起司蛋餅 55)
  ('d0000000-0000-0000-0000-000000000003',
   'c0000000-0000-0000-0000-0000000000e1',
   'a3333333-3333-3333-3333-333333333333',
   'tn-a', CURRENT_DATE - 1, 'picked_up', 55,
   (CURRENT_DATE - 1 + INTERVAL '9 hours')::timestamptz,
   (CURRENT_DATE - 1 + INTERVAL '17 hours')::timestamptz,
   (CURRENT_DATE - 1 + INTERVAL '11 hours')::timestamptz,
   (CURRENT_DATE - 1 + INTERVAL '12 hours')::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO order_item (order_id, menu_item_id, qty, unit_price_minor)
SELECT v.order_id, v.menu_item_id, 1, v.unit_price_minor
FROM (VALUES
  ('d0000000-0000-0000-0000-000000000001'::uuid, '4f26e612-b35f-5500-8f2a-63eded235675'::uuid, 165::bigint),
  ('d0000000-0000-0000-0000-000000000002'::uuid, '79722223-aa4b-5236-9964-9fcf0071c6ce'::uuid, 75::bigint),
  ('d0000000-0000-0000-0000-000000000003'::uuid, 'aeeb4dd3-c1c9-511e-a90d-31a06b4ee2ae'::uuid, 55::bigint)
) AS v(order_id, menu_item_id, unit_price_minor)
WHERE NOT EXISTS (
  SELECT 1 FROM order_item oi WHERE oi.order_id = v.order_id
);

COMMIT;
